// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.190111.3

#pragma once

WINRT_EXPORT namespace winrt::Windows::UI::Xaml::Interop {

struct TypeName;

}

WINRT_EXPORT namespace winrt::Windows::UI::Xaml::Markup {

struct IXamlType;
struct XmlnsDefinition;

}

WINRT_EXPORT namespace winrt::Windows::UI::Xaml::Markup {

struct IXamlMetadataProvider;

}

WINRT_EXPORT namespace winrt::CppWinRTComponent {

struct IMyNativeUserControl;
struct MyNativeUserControl;
struct XamlMetaDataProvider;

}

namespace winrt::impl {

template <> struct category<CppWinRTComponent::IMyNativeUserControl>{ using type = interface_category; };
template <> struct category<CppWinRTComponent::MyNativeUserControl>{ using type = class_category; };
template <> struct category<CppWinRTComponent::XamlMetaDataProvider>{ using type = class_category; };
template <> struct name<CppWinRTComponent::IMyNativeUserControl>{ static constexpr auto & value{ L"CppWinRTComponent.IMyNativeUserControl" }; };
template <> struct name<CppWinRTComponent::MyNativeUserControl>{ static constexpr auto & value{ L"CppWinRTComponent.MyNativeUserControl" }; };
template <> struct name<CppWinRTComponent::XamlMetaDataProvider>{ static constexpr auto & value{ L"CppWinRTComponent.XamlMetaDataProvider" }; };
template <> struct guid_storage<CppWinRTComponent::IMyNativeUserControl>{ static constexpr guid value{ 0x5F9A048D,0xD6F9,0x5515,{ 0xAD,0x97,0xDE,0x4D,0xC0,0x9B,0x8B,0xD3 } }; };
template <> struct default_interface<CppWinRTComponent::MyNativeUserControl>{ using type = CppWinRTComponent::IMyNativeUserControl; };
template <> struct default_interface<CppWinRTComponent::XamlMetaDataProvider>{ using type = Windows::UI::Xaml::Markup::IXamlMetadataProvider; };

template <> struct abi<CppWinRTComponent::IMyNativeUserControl>{ struct type : IInspectable
{
};};

template <typename D>
struct consume_CppWinRTComponent_IMyNativeUserControl
{
};
template <> struct consume<CppWinRTComponent::IMyNativeUserControl> { template <typename D> using type = consume_CppWinRTComponent_IMyNativeUserControl<D>; };

}
