// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.190111.3

#pragma once

#include "winrt/Windows.UI.Xaml.Interop.h"
#include "winrt/Windows.UI.Xaml.Markup.h"
#include "winrt/Microsoft.UI.Xaml.Markup.h"
#include "winrt/Windows.Foundation.h"
#include "winrt/Windows.UI.Composition.h"
#include "winrt/Windows.UI.Xaml.h"
#include "winrt/Windows.UI.Xaml.Controls.h"
#include "winrt/MyApp.h"

namespace winrt::MyApp::implementation {

template <typename D, typename... I>
struct WINRT_EBO App_base : implements<D, MyApp::IApp, Windows::UI::Xaml::IApplicationOverrides, Windows::UI::Xaml::IApplicationOverrides2, composing, I...>,
    impl::require<D, Microsoft::UI::Xaml::Markup::IXamlApplication, Microsoft::UI::Xaml::Markup::IXamlMetadataProviderContainer, Windows::Foundation::IClosable, Windows::UI::Xaml::IApplication, Windows::UI::Xaml::IApplication2, Windows::UI::Xaml::IApplication3, Windows::UI::Xaml::Markup::IXamlMetadataProvider>,
    impl::base<D, Microsoft::UI::Xaml::Markup::XamlApplication, Windows::UI::Xaml::Application>,
    Windows::UI::Xaml::IApplicationOverridesT<D>, Windows::UI::Xaml::IApplicationOverrides2T<D>
{
    using base_type = App_base;
    using class_type = MyApp::App;
    using implements_type = typename App_base::implements_type;
    using implements_type::implements_type;
    using composable_base = Microsoft::UI::Xaml::Markup::XamlApplication;
#if _MSC_VER < 1914
    operator class_type() const noexcept
    {
        static_assert(std::is_same_v<typename impl::implements_default_interface<D>::type, default_interface<class_type>>);
        class_type result{ nullptr };
        attach_abi(result, detach_abi(static_cast<default_interface<class_type>>(*this)));
        return result;
    }
#else
    operator impl::producer_ref<class_type> const() const noexcept
    {
        return { to_abi<default_interface<class_type>>(this) };
    }
#endif

    hstring GetRuntimeClassName() const
    {
        return L"MyApp.App";
    }
    App_base()
    {
        impl::call_factory<Microsoft::UI::Xaml::Markup::XamlApplication, Microsoft::UI::Xaml::Markup::IXamlApplicationFactory>([&](auto&& f) { f.CreateInstance(*this, this->m_inner); });
    }
    App_base(Windows::UI::Xaml::Markup::IXamlMetadataProvider const& parentProvider)
    {
        impl::call_factory<Microsoft::UI::Xaml::Markup::XamlApplication, Microsoft::UI::Xaml::Markup::IXamlApplicationFactory>([&](auto&& f) { f.CreateInstance2(parentProvider, *this, this->m_inner); });
    }
};

}

namespace winrt::MyApp::factory_implementation {

template <typename D, typename T, typename... I>
struct WINRT_EBO AppT : implements<D, Windows::Foundation::IActivationFactory, I...>
{
    using instance_type = MyApp::App;

    hstring GetRuntimeClassName() const
    {
        return L"MyApp.App";
    }

    Windows::Foundation::IInspectable ActivateInstance() const
    {
        return make<T>();
    }
};

}

#if defined(WINRT_FORCE_INCLUDE_APP_XAML_G_H) || __has_include("App.xaml.g.h")

#include "App.xaml.g.h"

#else

namespace winrt::MyApp::implementation
{
    template <typename D, typename... I>
    using AppT = App_base<D, I...>;
}

#endif
