// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.190111.3

#include "pch.h"
#include "winrt/base.h"

int32_t WINRT_CALL WINRT_CanUnloadNow() noexcept
{
    return 0; // S_OK
}

int32_t WINRT_CALL WINRT_GetActivationFactory(void*, void** factory) noexcept
{
    *factory = nullptr;
    return winrt::hresult_class_not_available().to_abi();
}
