// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.190111.3

#pragma once
#include "winrt/impl/Windows.UI.Xaml.Interop.0.h"
#include "winrt/impl/Windows.UI.Xaml.Markup.0.h"
#include "winrt/impl/Windows.Foundation.0.h"
#include "winrt/impl/Windows.UI.Xaml.0.h"
#include "winrt/impl/Microsoft.UI.Xaml.Markup.0.h"

WINRT_EXPORT namespace winrt::Microsoft::UI::Xaml::Markup {

struct WINRT_EBO IXamlApplication :
    Windows::Foundation::IInspectable,
    impl::consume_t<IXamlApplication>
{
    IXamlApplication(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IXamlMetadataProviderContainer :
    Windows::Foundation::IInspectable,
    impl::consume_t<IXamlMetadataProviderContainer>
{
    IXamlMetadataProviderContainer(std::nullptr_t = nullptr) noexcept {}
};

}
