// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.190111.3

#pragma once
#include "winrt/impl/Windows.UI.Xaml.Interop.0.h"
#include "winrt/impl/Windows.UI.Xaml.Markup.0.h"
#include "winrt/impl/Windows.UI.Composition.0.h"
#include "winrt/impl/Windows.UI.Xaml.0.h"
#include "winrt/impl/Windows.UI.Xaml.Controls.0.h"
#include "winrt/impl/SampleUserControl.0.h"

WINRT_EXPORT namespace winrt::SampleUserControl {

struct WINRT_EBO IMyUserControl :
    Windows::Foundation::IInspectable,
    impl::consume_t<IMyUserControl>
{
    IMyUserControl(std::nullptr_t = nullptr) noexcept {}
};

}
