// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.190111.3

#pragma once

WINRT_EXPORT namespace winrt::Windows::UI::Xaml::Interop {

struct TypeName;

}

WINRT_EXPORT namespace winrt::Windows::UI::Xaml::Markup {

struct IXamlType;
struct XmlnsDefinition;

}

WINRT_EXPORT namespace winrt::Windows::UI::Xaml::Markup {

struct IXamlMetadataProvider;

}

WINRT_EXPORT namespace winrt::SampleUserControl {

struct IInternalUserControl;
struct IMyUserControl;
struct InternalUserControl;
struct MyUserControl;
struct XamlMetaDataProvider;

}

namespace winrt::impl {

template <> struct category<SampleUserControl::IInternalUserControl>{ using type = interface_category; };
template <> struct category<SampleUserControl::IMyUserControl>{ using type = interface_category; };
template <> struct category<SampleUserControl::InternalUserControl>{ using type = class_category; };
template <> struct category<SampleUserControl::MyUserControl>{ using type = class_category; };
template <> struct category<SampleUserControl::XamlMetaDataProvider>{ using type = class_category; };
template <> struct name<SampleUserControl::IInternalUserControl>{ static constexpr auto & value{ L"SampleUserControl.IInternalUserControl" }; };
template <> struct name<SampleUserControl::IMyUserControl>{ static constexpr auto & value{ L"SampleUserControl.IMyUserControl" }; };
template <> struct name<SampleUserControl::InternalUserControl>{ static constexpr auto & value{ L"SampleUserControl.InternalUserControl" }; };
template <> struct name<SampleUserControl::MyUserControl>{ static constexpr auto & value{ L"SampleUserControl.MyUserControl" }; };
template <> struct name<SampleUserControl::XamlMetaDataProvider>{ static constexpr auto & value{ L"SampleUserControl.XamlMetaDataProvider" }; };
template <> struct guid_storage<SampleUserControl::IInternalUserControl>{ static constexpr guid value{ 0xDE19A9C7,0x616E,0x59A4,{ 0x86,0x63,0xE7,0x85,0x1E,0x4E,0x7F,0xF8 } }; };
template <> struct guid_storage<SampleUserControl::IMyUserControl>{ static constexpr guid value{ 0x6F0034F9,0xDCBD,0x523E,{ 0x82,0xC7,0xC4,0xE6,0x35,0x12,0xC4,0x1C } }; };
template <> struct default_interface<SampleUserControl::InternalUserControl>{ using type = SampleUserControl::IInternalUserControl; };
template <> struct default_interface<SampleUserControl::MyUserControl>{ using type = SampleUserControl::IMyUserControl; };
template <> struct default_interface<SampleUserControl::XamlMetaDataProvider>{ using type = Windows::UI::Xaml::Markup::IXamlMetadataProvider; };

template <> struct abi<SampleUserControl::IInternalUserControl>{ struct type : IInspectable
{
    virtual int32_t WINRT_CALL get_MyProperty(int32_t* value) noexcept = 0;
    virtual int32_t WINRT_CALL put_MyProperty(int32_t value) noexcept = 0;
};};

template <> struct abi<SampleUserControl::IMyUserControl>{ struct type : IInspectable
{
    virtual int32_t WINRT_CALL get_MyProperty(void** value) noexcept = 0;
    virtual int32_t WINRT_CALL put_MyProperty(void* value) noexcept = 0;
};};

template <typename D>
struct consume_SampleUserControl_IInternalUserControl
{
    int32_t MyProperty() const;
    void MyProperty(int32_t value) const;
};
template <> struct consume<SampleUserControl::IInternalUserControl> { template <typename D> using type = consume_SampleUserControl_IInternalUserControl<D>; };

template <typename D>
struct consume_SampleUserControl_IMyUserControl
{
    hstring MyProperty() const;
    void MyProperty(param::hstring const& value) const;
};
template <> struct consume<SampleUserControl::IMyUserControl> { template <typename D> using type = consume_SampleUserControl_IMyUserControl<D>; };

}
