// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.181115.3

#pragma once

#include "winrt/Windows.UI.Xaml.Interop.h"
#include "winrt/Windows.UI.Xaml.Markup.h"
#include "winrt/Windows.UI.Composition.h"
#include "winrt/Windows.UI.Xaml.h"
#include "winrt/Windows.UI.Xaml.Controls.h"
#include "winrt/NativeWinRTComponent.h"

namespace winrt::NativeWinRTComponent::implementation {

template <typename D, typename... I>
struct WINRT_EBO Class_base : implements<D, NativeWinRTComponent::IClass, I...>
{
    using base_type = Class_base;
    using class_type = NativeWinRTComponent::Class;
    using implements_type = typename Class_base::implements_type;
    using implements_type::implements_type;
    
#if _MSC_VER < 1914
    operator class_type() const noexcept
    {
        static_assert(std::is_same_v<typename impl::implements_default_interface<D>::type, default_interface<class_type>>);
        class_type result{ nullptr };
        attach_abi(result, detach_abi(static_cast<default_interface<class_type>>(*this)));
        return result;
    }
#else
    operator impl::producer_ref<class_type> const() const noexcept
    {
        return { to_abi<default_interface<class_type>>(this) };
    }
#endif

    hstring GetRuntimeClassName() const
    {
        return L"NativeWinRTComponent.Class";
    }
};

}

namespace winrt::NativeWinRTComponent::factory_implementation {

template <typename D, typename T, typename... I>
struct WINRT_EBO ClassT : implements<D, Windows::Foundation::IActivationFactory, I...>
{
    using instance_type = NativeWinRTComponent::Class;

    hstring GetRuntimeClassName() const
    {
        return L"NativeWinRTComponent.Class";
    }

    Windows::Foundation::IInspectable ActivateInstance() const
    {
        return make<T>();
    }
};

}

#if defined(WINRT_FORCE_INCLUDE_CLASS_XAML_G_H) || __has_include("Class.xaml.g.h")

#include "Class.xaml.g.h"

#else

namespace winrt::NativeWinRTComponent::implementation
{
    template <typename D, typename... I>
    using ClassT = Class_base<D, I...>;
}

#endif
