// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.190111.3

#pragma once
#include "winrt/impl/Microsoft.UI.Xaml.Controls.0.h"
#include "winrt/impl/Microsoft.UI.Xaml.Controls.Primitives.0.h"
#include "winrt/impl/Windows.UI.Xaml.Automation.0.h"
#include "winrt/impl/Windows.UI.Xaml.0.h"
#include "winrt/impl/Windows.UI.Xaml.Automation.Peers.0.h"
#include "winrt/impl/Windows.UI.Xaml.Automation.Provider.0.h"
#include "winrt/impl/Microsoft.UI.Xaml.Automation.Peers.0.h"

WINRT_EXPORT namespace winrt::Microsoft::UI::Xaml::Automation::Peers {

struct WINRT_EBO IAnimatedVisualPlayerAutomationPeer :
    Windows::Foundation::IInspectable,
    impl::consume_t<IAnimatedVisualPlayerAutomationPeer>
{
    IAnimatedVisualPlayerAutomationPeer(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IAnimatedVisualPlayerAutomationPeerFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IAnimatedVisualPlayerAutomationPeerFactory>
{
    IAnimatedVisualPlayerAutomationPeerFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IColorPickerSliderAutomationPeer :
    Windows::Foundation::IInspectable,
    impl::consume_t<IColorPickerSliderAutomationPeer>
{
    IColorPickerSliderAutomationPeer(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IColorPickerSliderAutomationPeerFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IColorPickerSliderAutomationPeerFactory>
{
    IColorPickerSliderAutomationPeerFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IColorSpectrumAutomationPeer :
    Windows::Foundation::IInspectable,
    impl::consume_t<IColorSpectrumAutomationPeer>
{
    IColorSpectrumAutomationPeer(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IColorSpectrumAutomationPeerFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IColorSpectrumAutomationPeerFactory>
{
    IColorSpectrumAutomationPeerFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IDropDownButtonAutomationPeer :
    Windows::Foundation::IInspectable,
    impl::consume_t<IDropDownButtonAutomationPeer>
{
    IDropDownButtonAutomationPeer(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IDropDownButtonAutomationPeerFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IDropDownButtonAutomationPeerFactory>
{
    IDropDownButtonAutomationPeerFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IMenuBarAutomationPeer :
    Windows::Foundation::IInspectable,
    impl::consume_t<IMenuBarAutomationPeer>
{
    IMenuBarAutomationPeer(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IMenuBarAutomationPeerFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IMenuBarAutomationPeerFactory>
{
    IMenuBarAutomationPeerFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IMenuBarItemAutomationPeer :
    Windows::Foundation::IInspectable,
    impl::consume_t<IMenuBarItemAutomationPeer>
{
    IMenuBarItemAutomationPeer(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IMenuBarItemAutomationPeerFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IMenuBarItemAutomationPeerFactory>
{
    IMenuBarItemAutomationPeerFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO INavigationViewItemAutomationPeer :
    Windows::Foundation::IInspectable,
    impl::consume_t<INavigationViewItemAutomationPeer>
{
    INavigationViewItemAutomationPeer(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO INavigationViewItemAutomationPeerFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<INavigationViewItemAutomationPeerFactory>
{
    INavigationViewItemAutomationPeerFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IPersonPictureAutomationPeer :
    Windows::Foundation::IInspectable,
    impl::consume_t<IPersonPictureAutomationPeer>
{
    IPersonPictureAutomationPeer(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IPersonPictureAutomationPeerFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IPersonPictureAutomationPeerFactory>
{
    IPersonPictureAutomationPeerFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRadioButtonsListViewItemAutomationPeer :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRadioButtonsListViewItemAutomationPeer>
{
    IRadioButtonsListViewItemAutomationPeer(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRadioButtonsListViewItemAutomationPeerFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRadioButtonsListViewItemAutomationPeerFactory>
{
    IRadioButtonsListViewItemAutomationPeerFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRatingControlAutomationPeer :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRatingControlAutomationPeer>
{
    IRatingControlAutomationPeer(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRatingControlAutomationPeerFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRatingControlAutomationPeerFactory>
{
    IRatingControlAutomationPeerFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRepeaterAutomationPeer :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRepeaterAutomationPeer>
{
    IRepeaterAutomationPeer(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRepeaterAutomationPeerFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRepeaterAutomationPeerFactory>
{
    IRepeaterAutomationPeerFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IScrollerAutomationPeer :
    Windows::Foundation::IInspectable,
    impl::consume_t<IScrollerAutomationPeer>
{
    IScrollerAutomationPeer(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IScrollerAutomationPeerFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IScrollerAutomationPeerFactory>
{
    IScrollerAutomationPeerFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISplitButtonAutomationPeer :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISplitButtonAutomationPeer>
{
    ISplitButtonAutomationPeer(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISplitButtonAutomationPeerFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISplitButtonAutomationPeerFactory>
{
    ISplitButtonAutomationPeerFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ITeachingTipAutomationPeer :
    Windows::Foundation::IInspectable,
    impl::consume_t<ITeachingTipAutomationPeer>
{
    ITeachingTipAutomationPeer(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ITeachingTipAutomationPeerFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<ITeachingTipAutomationPeerFactory>
{
    ITeachingTipAutomationPeerFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IToggleSplitButtonAutomationPeer :
    Windows::Foundation::IInspectable,
    impl::consume_t<IToggleSplitButtonAutomationPeer>
{
    IToggleSplitButtonAutomationPeer(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IToggleSplitButtonAutomationPeerFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IToggleSplitButtonAutomationPeerFactory>
{
    IToggleSplitButtonAutomationPeerFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ITreeViewItemAutomationPeer :
    Windows::Foundation::IInspectable,
    impl::consume_t<ITreeViewItemAutomationPeer>
{
    ITreeViewItemAutomationPeer(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ITreeViewItemAutomationPeerFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<ITreeViewItemAutomationPeerFactory>
{
    ITreeViewItemAutomationPeerFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ITreeViewListAutomationPeer :
    Windows::Foundation::IInspectable,
    impl::consume_t<ITreeViewListAutomationPeer>
{
    ITreeViewListAutomationPeer(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ITreeViewListAutomationPeerFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<ITreeViewListAutomationPeerFactory>
{
    ITreeViewListAutomationPeerFactory(std::nullptr_t = nullptr) noexcept {}
};

}
