// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.190111.3

#pragma once
#include "winrt/impl/Windows.UI.0.h"
#include "winrt/impl/Windows.UI.Xaml.0.h"
#include "winrt/impl/Windows.UI.Composition.0.h"
#include "winrt/impl/Windows.UI.Xaml.Media.0.h"
#include "winrt/impl/Microsoft.UI.Xaml.Media.0.h"

WINRT_EXPORT namespace winrt::Microsoft::UI::Xaml::Media {

struct WINRT_EBO IAcrylicBrush :
    Windows::Foundation::IInspectable,
    impl::consume_t<IAcrylicBrush>
{
    IAcrylicBrush(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IAcrylicBrushFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IAcrylicBrushFactory>
{
    IAcrylicBrushFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IAcrylicBrushStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<IAcrylicBrushStatics>
{
    IAcrylicBrushStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRevealBackgroundBrush :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRevealBackgroundBrush>
{
    IRevealBackgroundBrush(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRevealBackgroundBrushFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRevealBackgroundBrushFactory>
{
    IRevealBackgroundBrushFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRevealBorderBrush :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRevealBorderBrush>
{
    IRevealBorderBrush(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRevealBorderBrushFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRevealBorderBrushFactory>
{
    IRevealBorderBrushFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRevealBrush :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRevealBrush>
{
    IRevealBrush(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRevealBrushProtectedFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRevealBrushProtectedFactory>
{
    IRevealBrushProtectedFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRevealBrushStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRevealBrushStatics>
{
    IRevealBrushStatics(std::nullptr_t = nullptr) noexcept {}
};

}
