// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.190111.3

#pragma once
#include "winrt/impl/Microsoft.UI.Xaml.Controls.Primitives.0.h"
#include "winrt/impl/Windows.ApplicationModel.Contacts.0.h"
#include "winrt/impl/Windows.ApplicationModel.DataTransfer.0.h"
#include "winrt/impl/Windows.Foundation.0.h"
#include "winrt/impl/Windows.UI.0.h"
#include "winrt/impl/Windows.UI.Composition.0.h"
#include "winrt/impl/Windows.UI.Text.0.h"
#include "winrt/impl/Windows.UI.Xaml.0.h"
#include "winrt/impl/Windows.UI.Xaml.Controls.0.h"
#include "winrt/impl/Windows.UI.Xaml.Controls.Primitives.0.h"
#include "winrt/impl/Windows.UI.Xaml.Data.0.h"
#include "winrt/impl/Windows.UI.Xaml.Input.0.h"
#include "winrt/impl/Windows.UI.Xaml.Interop.0.h"
#include "winrt/impl/Windows.UI.Xaml.Media.0.h"
#include "winrt/impl/Windows.UI.Xaml.Media.Animation.0.h"
#include "winrt/impl/Windows.Foundation.Collections.0.h"
#include "winrt/impl/Microsoft.UI.Xaml.Controls.0.h"

WINRT_EXPORT namespace winrt::Microsoft::UI::Xaml::Controls {

struct WINRT_EBO IAnimatedVisual :
    Windows::Foundation::IInspectable,
    impl::consume_t<IAnimatedVisual>,
    impl::require<IAnimatedVisual, Windows::Foundation::IClosable>
{
    IAnimatedVisual(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IAnimatedVisualPlayer :
    Windows::Foundation::IInspectable,
    impl::consume_t<IAnimatedVisualPlayer>
{
    IAnimatedVisualPlayer(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IAnimatedVisualPlayerFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IAnimatedVisualPlayerFactory>
{
    IAnimatedVisualPlayerFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IAnimatedVisualPlayerStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<IAnimatedVisualPlayerStatics>
{
    IAnimatedVisualPlayerStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IAnimatedVisualSource :
    Windows::Foundation::IInspectable,
    impl::consume_t<IAnimatedVisualSource>
{
    IAnimatedVisualSource(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IBitmapIconSource :
    Windows::Foundation::IInspectable,
    impl::consume_t<IBitmapIconSource>
{
    IBitmapIconSource(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IBitmapIconSourceFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IBitmapIconSourceFactory>
{
    IBitmapIconSourceFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IBitmapIconSourceStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<IBitmapIconSourceStatics>
{
    IBitmapIconSourceStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IColorChangedEventArgs :
    Windows::Foundation::IInspectable,
    impl::consume_t<IColorChangedEventArgs>
{
    IColorChangedEventArgs(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IColorPicker :
    Windows::Foundation::IInspectable,
    impl::consume_t<IColorPicker>
{
    IColorPicker(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IColorPickerFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IColorPickerFactory>
{
    IColorPickerFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IColorPickerStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<IColorPickerStatics>
{
    IColorPickerStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ICommandBarFlyout :
    Windows::Foundation::IInspectable,
    impl::consume_t<ICommandBarFlyout>
{
    ICommandBarFlyout(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ICommandBarFlyoutFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<ICommandBarFlyoutFactory>
{
    ICommandBarFlyoutFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IDropDownButton :
    Windows::Foundation::IInspectable,
    impl::consume_t<IDropDownButton>
{
    IDropDownButton(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IDropDownButtonFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IDropDownButtonFactory>
{
    IDropDownButtonFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IDynamicAnimatedVisualSource :
    Windows::Foundation::IInspectable,
    impl::consume_t<IDynamicAnimatedVisualSource>,
    impl::require<IDynamicAnimatedVisualSource, Microsoft::UI::Xaml::Controls::IAnimatedVisualSource>
{
    IDynamicAnimatedVisualSource(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IElementAnimator :
    Windows::Foundation::IInspectable,
    impl::consume_t<IElementAnimator>
{
    IElementAnimator(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IElementAnimatorFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IElementAnimatorFactory>
{
    IElementAnimatorFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IElementAnimatorOverrides :
    Windows::Foundation::IInspectable,
    impl::consume_t<IElementAnimatorOverrides>
{
    IElementAnimatorOverrides(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IElementAnimatorProtected :
    Windows::Foundation::IInspectable,
    impl::consume_t<IElementAnimatorProtected>
{
    IElementAnimatorProtected(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IElementFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IElementFactory>
{
    IElementFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IElementFactoryFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IElementFactoryFactory>
{
    IElementFactoryFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IElementFactoryGetArgs :
    Windows::Foundation::IInspectable,
    impl::consume_t<IElementFactoryGetArgs>
{
    IElementFactoryGetArgs(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IElementFactoryOverrides :
    Windows::Foundation::IInspectable,
    impl::consume_t<IElementFactoryOverrides>
{
    IElementFactoryOverrides(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IElementFactoryRecycleArgs :
    Windows::Foundation::IInspectable,
    impl::consume_t<IElementFactoryRecycleArgs>
{
    IElementFactoryRecycleArgs(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IElementFactoryShim :
    Windows::Foundation::IInspectable,
    impl::consume_t<IElementFactoryShim>
{
    IElementFactoryShim(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IFlowLayout :
    Windows::Foundation::IInspectable,
    impl::consume_t<IFlowLayout>
{
    IFlowLayout(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IFlowLayoutFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IFlowLayoutFactory>
{
    IFlowLayoutFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IFlowLayoutOverrides :
    Windows::Foundation::IInspectable,
    impl::consume_t<IFlowLayoutOverrides>
{
    IFlowLayoutOverrides(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IFlowLayoutState :
    Windows::Foundation::IInspectable,
    impl::consume_t<IFlowLayoutState>
{
    IFlowLayoutState(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IFlowLayoutStateFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IFlowLayoutStateFactory>
{
    IFlowLayoutStateFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IFlowLayoutStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<IFlowLayoutStatics>
{
    IFlowLayoutStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IFontIconSource :
    Windows::Foundation::IInspectable,
    impl::consume_t<IFontIconSource>
{
    IFontIconSource(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IFontIconSourceFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IFontIconSourceFactory>
{
    IFontIconSourceFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IFontIconSourceStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<IFontIconSourceStatics>
{
    IFontIconSourceStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IIconSource :
    Windows::Foundation::IInspectable,
    impl::consume_t<IIconSource>
{
    IIconSource(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IIconSourceFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IIconSourceFactory>
{
    IIconSourceFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IIconSourceStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<IIconSourceStatics>
{
    IIconSourceStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IIndexPath :
    Windows::Foundation::IInspectable,
    impl::consume_t<IIndexPath>
{
    IIndexPath(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IIndexPathStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<IIndexPathStatics>
{
    IIndexPathStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IItemsRepeater :
    Windows::Foundation::IInspectable,
    impl::consume_t<IItemsRepeater>
{
    IItemsRepeater(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IItemsRepeater2 :
    Windows::Foundation::IInspectable,
    impl::consume_t<IItemsRepeater2>
{
    IItemsRepeater2(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IItemsRepeaterElementClearingEventArgs :
    Windows::Foundation::IInspectable,
    impl::consume_t<IItemsRepeaterElementClearingEventArgs>
{
    IItemsRepeaterElementClearingEventArgs(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IItemsRepeaterElementIndexChangedEventArgs :
    Windows::Foundation::IInspectable,
    impl::consume_t<IItemsRepeaterElementIndexChangedEventArgs>
{
    IItemsRepeaterElementIndexChangedEventArgs(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IItemsRepeaterElementPreparedEventArgs :
    Windows::Foundation::IInspectable,
    impl::consume_t<IItemsRepeaterElementPreparedEventArgs>
{
    IItemsRepeaterElementPreparedEventArgs(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IItemsRepeaterFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IItemsRepeaterFactory>
{
    IItemsRepeaterFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IItemsRepeaterStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<IItemsRepeaterStatics>
{
    IItemsRepeaterStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IItemsSourceView :
    Windows::Foundation::IInspectable,
    impl::consume_t<IItemsSourceView>
{
    IItemsSourceView(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IItemsSourceViewFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IItemsSourceViewFactory>
{
    IItemsSourceViewFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IKeyIndexMapping :
    Windows::Foundation::IInspectable,
    impl::consume_t<IKeyIndexMapping>
{
    IKeyIndexMapping(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ILayout :
    Windows::Foundation::IInspectable,
    impl::consume_t<ILayout>
{
    ILayout(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ILayoutContext :
    Windows::Foundation::IInspectable,
    impl::consume_t<ILayoutContext>
{
    ILayoutContext(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ILayoutContextFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<ILayoutContextFactory>
{
    ILayoutContextFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ILayoutContextOverrides :
    Windows::Foundation::IInspectable,
    impl::consume_t<ILayoutContextOverrides>
{
    ILayoutContextOverrides(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ILayoutFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<ILayoutFactory>
{
    ILayoutFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ILayoutPanel :
    Windows::Foundation::IInspectable,
    impl::consume_t<ILayoutPanel>
{
    ILayoutPanel(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ILayoutPanelFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<ILayoutPanelFactory>
{
    ILayoutPanelFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ILayoutPanelStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<ILayoutPanelStatics>
{
    ILayoutPanelStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ILayoutProtected :
    Windows::Foundation::IInspectable,
    impl::consume_t<ILayoutProtected>
{
    ILayoutProtected(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IMenuBar :
    Windows::Foundation::IInspectable,
    impl::consume_t<IMenuBar>
{
    IMenuBar(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IMenuBarFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IMenuBarFactory>
{
    IMenuBarFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IMenuBarItem :
    Windows::Foundation::IInspectable,
    impl::consume_t<IMenuBarItem>
{
    IMenuBarItem(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IMenuBarItemFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IMenuBarItemFactory>
{
    IMenuBarItemFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IMenuBarItemFlyout :
    Windows::Foundation::IInspectable,
    impl::consume_t<IMenuBarItemFlyout>
{
    IMenuBarItemFlyout(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IMenuBarItemFlyoutFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IMenuBarItemFlyoutFactory>
{
    IMenuBarItemFlyoutFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IMenuBarItemStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<IMenuBarItemStatics>
{
    IMenuBarItemStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IMenuBarStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<IMenuBarStatics>
{
    IMenuBarStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO INavigationView :
    Windows::Foundation::IInspectable,
    impl::consume_t<INavigationView>
{
    INavigationView(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO INavigationViewBackRequestedEventArgs :
    Windows::Foundation::IInspectable,
    impl::consume_t<INavigationViewBackRequestedEventArgs>
{
    INavigationViewBackRequestedEventArgs(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO INavigationViewDisplayModeChangedEventArgs :
    Windows::Foundation::IInspectable,
    impl::consume_t<INavigationViewDisplayModeChangedEventArgs>
{
    INavigationViewDisplayModeChangedEventArgs(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO INavigationViewFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<INavigationViewFactory>
{
    INavigationViewFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO INavigationViewItem :
    Windows::Foundation::IInspectable,
    impl::consume_t<INavigationViewItem>
{
    INavigationViewItem(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO INavigationViewItemBase :
    Windows::Foundation::IInspectable,
    impl::consume_t<INavigationViewItemBase>
{
    INavigationViewItemBase(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO INavigationViewItemBaseFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<INavigationViewItemBaseFactory>
{
    INavigationViewItemBaseFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO INavigationViewItemFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<INavigationViewItemFactory>
{
    INavigationViewItemFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO INavigationViewItemHeader :
    Windows::Foundation::IInspectable,
    impl::consume_t<INavigationViewItemHeader>
{
    INavigationViewItemHeader(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO INavigationViewItemHeaderFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<INavigationViewItemHeaderFactory>
{
    INavigationViewItemHeaderFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO INavigationViewItemInvokedEventArgs :
    Windows::Foundation::IInspectable,
    impl::consume_t<INavigationViewItemInvokedEventArgs>
{
    INavigationViewItemInvokedEventArgs(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO INavigationViewItemSeparator :
    Windows::Foundation::IInspectable,
    impl::consume_t<INavigationViewItemSeparator>
{
    INavigationViewItemSeparator(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO INavigationViewItemSeparatorFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<INavigationViewItemSeparatorFactory>
{
    INavigationViewItemSeparatorFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO INavigationViewItemStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<INavigationViewItemStatics>
{
    INavigationViewItemStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO INavigationViewList :
    Windows::Foundation::IInspectable,
    impl::consume_t<INavigationViewList>
{
    INavigationViewList(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO INavigationViewListFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<INavigationViewListFactory>
{
    INavigationViewListFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO INavigationViewPaneClosingEventArgs :
    Windows::Foundation::IInspectable,
    impl::consume_t<INavigationViewPaneClosingEventArgs>
{
    INavigationViewPaneClosingEventArgs(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO INavigationViewSelectionChangedEventArgs :
    Windows::Foundation::IInspectable,
    impl::consume_t<INavigationViewSelectionChangedEventArgs>
{
    INavigationViewSelectionChangedEventArgs(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO INavigationViewStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<INavigationViewStatics>
{
    INavigationViewStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO INavigationViewTemplateSettings :
    Windows::Foundation::IInspectable,
    impl::consume_t<INavigationViewTemplateSettings>
{
    INavigationViewTemplateSettings(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO INavigationViewTemplateSettingsFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<INavigationViewTemplateSettingsFactory>
{
    INavigationViewTemplateSettingsFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO INavigationViewTemplateSettingsStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<INavigationViewTemplateSettingsStatics>
{
    INavigationViewTemplateSettingsStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO INonVirtualizingLayout :
    Windows::Foundation::IInspectable,
    impl::consume_t<INonVirtualizingLayout>
{
    INonVirtualizingLayout(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO INonVirtualizingLayoutContext :
    Windows::Foundation::IInspectable,
    impl::consume_t<INonVirtualizingLayoutContext>
{
    INonVirtualizingLayoutContext(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO INonVirtualizingLayoutContextFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<INonVirtualizingLayoutContextFactory>
{
    INonVirtualizingLayoutContextFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO INonVirtualizingLayoutContextOverrides :
    Windows::Foundation::IInspectable,
    impl::consume_t<INonVirtualizingLayoutContextOverrides>
{
    INonVirtualizingLayoutContextOverrides(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO INonVirtualizingLayoutFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<INonVirtualizingLayoutFactory>
{
    INonVirtualizingLayoutFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO INonVirtualizingLayoutOverrides :
    Windows::Foundation::IInspectable,
    impl::consume_t<INonVirtualizingLayoutOverrides>
{
    INonVirtualizingLayoutOverrides(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IParallaxView :
    Windows::Foundation::IInspectable,
    impl::consume_t<IParallaxView>
{
    IParallaxView(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IParallaxViewFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IParallaxViewFactory>
{
    IParallaxViewFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IParallaxViewStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<IParallaxViewStatics>
{
    IParallaxViewStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IPathIconSource :
    Windows::Foundation::IInspectable,
    impl::consume_t<IPathIconSource>
{
    IPathIconSource(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IPathIconSourceFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IPathIconSourceFactory>
{
    IPathIconSourceFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IPathIconSourceStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<IPathIconSourceStatics>
{
    IPathIconSourceStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IPersonPicture :
    Windows::Foundation::IInspectable,
    impl::consume_t<IPersonPicture>
{
    IPersonPicture(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IPersonPictureFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IPersonPictureFactory>
{
    IPersonPictureFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IPersonPictureStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<IPersonPictureStatics>
{
    IPersonPictureStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IPersonPictureTemplateSettings :
    Windows::Foundation::IInspectable,
    impl::consume_t<IPersonPictureTemplateSettings>
{
    IPersonPictureTemplateSettings(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRadioButtons :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRadioButtons>
{
    IRadioButtons(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRadioButtonsFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRadioButtonsFactory>
{
    IRadioButtonsFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRadioButtonsStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRadioButtonsStatics>
{
    IRadioButtonsStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRadioMenuFlyoutItem :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRadioMenuFlyoutItem>
{
    IRadioMenuFlyoutItem(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRadioMenuFlyoutItemFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRadioMenuFlyoutItemFactory>
{
    IRadioMenuFlyoutItemFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRadioMenuFlyoutItemStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRadioMenuFlyoutItemStatics>
{
    IRadioMenuFlyoutItemStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRatingControl :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRatingControl>
{
    IRatingControl(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRatingControlFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRatingControlFactory>
{
    IRatingControlFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRatingControlStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRatingControlStatics>
{
    IRatingControlStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRatingItemFontInfo :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRatingItemFontInfo>
{
    IRatingItemFontInfo(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRatingItemFontInfoFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRatingItemFontInfoFactory>
{
    IRatingItemFontInfoFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRatingItemFontInfoStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRatingItemFontInfoStatics>
{
    IRatingItemFontInfoStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRatingItemImageInfo :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRatingItemImageInfo>
{
    IRatingItemImageInfo(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRatingItemImageInfoFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRatingItemImageInfoFactory>
{
    IRatingItemImageInfoFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRatingItemImageInfoStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRatingItemImageInfoStatics>
{
    IRatingItemImageInfoStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRatingItemInfo :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRatingItemInfo>
{
    IRatingItemInfo(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRatingItemInfoFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRatingItemInfoFactory>
{
    IRatingItemInfoFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRecyclePool :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRecyclePool>
{
    IRecyclePool(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRecyclePoolFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRecyclePoolFactory>
{
    IRecyclePoolFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRecyclePoolOverrides :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRecyclePoolOverrides>
{
    IRecyclePoolOverrides(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRecyclePoolStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRecyclePoolStatics>
{
    IRecyclePoolStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRecyclingElementFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRecyclingElementFactory>
{
    IRecyclingElementFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRecyclingElementFactoryFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRecyclingElementFactoryFactory>
{
    IRecyclingElementFactoryFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRecyclingElementFactoryOverrides :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRecyclingElementFactoryOverrides>
{
    IRecyclingElementFactoryOverrides(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRefreshContainer :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRefreshContainer>
{
    IRefreshContainer(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRefreshContainerFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRefreshContainerFactory>
{
    IRefreshContainerFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRefreshContainerStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRefreshContainerStatics>
{
    IRefreshContainerStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRefreshInteractionRatioChangedEventArgs :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRefreshInteractionRatioChangedEventArgs>
{
    IRefreshInteractionRatioChangedEventArgs(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRefreshRequestedEventArgs :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRefreshRequestedEventArgs>
{
    IRefreshRequestedEventArgs(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRefreshStateChangedEventArgs :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRefreshStateChangedEventArgs>
{
    IRefreshStateChangedEventArgs(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRefreshVisualizer :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRefreshVisualizer>
{
    IRefreshVisualizer(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRefreshVisualizerFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRefreshVisualizerFactory>
{
    IRefreshVisualizerFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRefreshVisualizerStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRefreshVisualizerStatics>
{
    IRefreshVisualizerStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRevealListViewItemPresenter :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRevealListViewItemPresenter>
{
    IRevealListViewItemPresenter(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRevealListViewItemPresenterFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRevealListViewItemPresenterFactory>
{
    IRevealListViewItemPresenterFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IScrollAnchorProvider :
    Windows::Foundation::IInspectable,
    impl::consume_t<IScrollAnchorProvider>
{
    IScrollAnchorProvider(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IScrollAnimationStartingEventArgs :
    Windows::Foundation::IInspectable,
    impl::consume_t<IScrollAnimationStartingEventArgs>
{
    IScrollAnimationStartingEventArgs(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IScrollCompletedEventArgs :
    Windows::Foundation::IInspectable,
    impl::consume_t<IScrollCompletedEventArgs>
{
    IScrollCompletedEventArgs(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IScrollOptions :
    Windows::Foundation::IInspectable,
    impl::consume_t<IScrollOptions>
{
    IScrollOptions(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IScrollOptionsFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IScrollOptionsFactory>
{
    IScrollOptionsFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IScrollViewer :
    Windows::Foundation::IInspectable,
    impl::consume_t<IScrollViewer>
{
    IScrollViewer(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IScrollViewerFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IScrollViewerFactory>
{
    IScrollViewerFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IScrollViewerStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<IScrollViewerStatics>
{
    IScrollViewerStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IScrollerAnchorRequestedEventArgs :
    Windows::Foundation::IInspectable,
    impl::consume_t<IScrollerAnchorRequestedEventArgs>
{
    IScrollerAnchorRequestedEventArgs(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IScrollerBringingIntoViewEventArgs :
    Windows::Foundation::IInspectable,
    impl::consume_t<IScrollerBringingIntoViewEventArgs>
{
    IScrollerBringingIntoViewEventArgs(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISelectTemplateEventArgs :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISelectTemplateEventArgs>
{
    ISelectTemplateEventArgs(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISelectionModel :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISelectionModel>
{
    ISelectionModel(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISelectionModelChildrenRequestedEventArgs :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISelectionModelChildrenRequestedEventArgs>
{
    ISelectionModelChildrenRequestedEventArgs(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISelectionModelFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISelectionModelFactory>
{
    ISelectionModelFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISelectionModelProtected :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISelectionModelProtected>
{
    ISelectionModelProtected(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISelectionModelSelectionChangedEventArgs :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISelectionModelSelectionChangedEventArgs>
{
    ISelectionModelSelectionChangedEventArgs(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISelfPlayingAnimatedVisual :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISelfPlayingAnimatedVisual>,
    impl::require<ISelfPlayingAnimatedVisual, Microsoft::UI::Xaml::Controls::IAnimatedVisual, Windows::Foundation::IClosable>
{
    ISelfPlayingAnimatedVisual(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISplitButton :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISplitButton>
{
    ISplitButton(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISplitButtonClickEventArgs :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISplitButtonClickEventArgs>
{
    ISplitButtonClickEventArgs(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISplitButtonFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISplitButtonFactory>
{
    ISplitButtonFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISplitButtonStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISplitButtonStatics>
{
    ISplitButtonStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IStackLayout :
    Windows::Foundation::IInspectable,
    impl::consume_t<IStackLayout>
{
    IStackLayout(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IStackLayoutFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IStackLayoutFactory>
{
    IStackLayoutFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IStackLayoutState :
    Windows::Foundation::IInspectable,
    impl::consume_t<IStackLayoutState>
{
    IStackLayoutState(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IStackLayoutStateFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IStackLayoutStateFactory>
{
    IStackLayoutStateFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IStackLayoutStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<IStackLayoutStatics>
{
    IStackLayoutStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISwipeControl :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISwipeControl>
{
    ISwipeControl(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISwipeControlFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISwipeControlFactory>
{
    ISwipeControlFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISwipeControlStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISwipeControlStatics>
{
    ISwipeControlStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISwipeItem :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISwipeItem>
{
    ISwipeItem(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISwipeItemFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISwipeItemFactory>
{
    ISwipeItemFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISwipeItemInvokedEventArgs :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISwipeItemInvokedEventArgs>
{
    ISwipeItemInvokedEventArgs(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISwipeItemStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISwipeItemStatics>
{
    ISwipeItemStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISwipeItems :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISwipeItems>
{
    ISwipeItems(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISwipeItemsFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISwipeItemsFactory>
{
    ISwipeItemsFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISwipeItemsStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISwipeItemsStatics>
{
    ISwipeItemsStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISymbolIconSource :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISymbolIconSource>
{
    ISymbolIconSource(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISymbolIconSourceFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISymbolIconSourceFactory>
{
    ISymbolIconSourceFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISymbolIconSourceStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISymbolIconSourceStatics>
{
    ISymbolIconSourceStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ITeachingTip :
    Windows::Foundation::IInspectable,
    impl::consume_t<ITeachingTip>
{
    ITeachingTip(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ITeachingTipClosedEventArgs :
    Windows::Foundation::IInspectable,
    impl::consume_t<ITeachingTipClosedEventArgs>
{
    ITeachingTipClosedEventArgs(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ITeachingTipClosingEventArgs :
    Windows::Foundation::IInspectable,
    impl::consume_t<ITeachingTipClosingEventArgs>
{
    ITeachingTipClosingEventArgs(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ITeachingTipFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<ITeachingTipFactory>
{
    ITeachingTipFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ITeachingTipStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<ITeachingTipStatics>
{
    ITeachingTipStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ITeachingTipTemplateSettings :
    Windows::Foundation::IInspectable,
    impl::consume_t<ITeachingTipTemplateSettings>
{
    ITeachingTipTemplateSettings(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ITeachingTipTemplateSettingsFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<ITeachingTipTemplateSettingsFactory>
{
    ITeachingTipTemplateSettingsFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ITeachingTipTemplateSettingsStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<ITeachingTipTemplateSettingsStatics>
{
    ITeachingTipTemplateSettingsStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ITextCommandBarFlyout :
    Windows::Foundation::IInspectable,
    impl::consume_t<ITextCommandBarFlyout>
{
    ITextCommandBarFlyout(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ITextCommandBarFlyoutFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<ITextCommandBarFlyoutFactory>
{
    ITextCommandBarFlyoutFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IToggleSplitButton :
    Windows::Foundation::IInspectable,
    impl::consume_t<IToggleSplitButton>
{
    IToggleSplitButton(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IToggleSplitButtonFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IToggleSplitButtonFactory>
{
    IToggleSplitButtonFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IToggleSplitButtonIsCheckedChangedEventArgs :
    Windows::Foundation::IInspectable,
    impl::consume_t<IToggleSplitButtonIsCheckedChangedEventArgs>
{
    IToggleSplitButtonIsCheckedChangedEventArgs(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ITreeView :
    Windows::Foundation::IInspectable,
    impl::consume_t<ITreeView>
{
    ITreeView(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ITreeViewCollapsedEventArgs :
    Windows::Foundation::IInspectable,
    impl::consume_t<ITreeViewCollapsedEventArgs>
{
    ITreeViewCollapsedEventArgs(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ITreeViewDragItemsCompletedEventArgs :
    Windows::Foundation::IInspectable,
    impl::consume_t<ITreeViewDragItemsCompletedEventArgs>
{
    ITreeViewDragItemsCompletedEventArgs(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ITreeViewDragItemsStartingEventArgs :
    Windows::Foundation::IInspectable,
    impl::consume_t<ITreeViewDragItemsStartingEventArgs>
{
    ITreeViewDragItemsStartingEventArgs(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ITreeViewExpandingEventArgs :
    Windows::Foundation::IInspectable,
    impl::consume_t<ITreeViewExpandingEventArgs>
{
    ITreeViewExpandingEventArgs(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ITreeViewFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<ITreeViewFactory>
{
    ITreeViewFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ITreeViewItem :
    Windows::Foundation::IInspectable,
    impl::consume_t<ITreeViewItem>
{
    ITreeViewItem(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ITreeViewItemFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<ITreeViewItemFactory>
{
    ITreeViewItemFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ITreeViewItemInvokedEventArgs :
    Windows::Foundation::IInspectable,
    impl::consume_t<ITreeViewItemInvokedEventArgs>
{
    ITreeViewItemInvokedEventArgs(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ITreeViewItemStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<ITreeViewItemStatics>
{
    ITreeViewItemStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ITreeViewItemTemplateSettings :
    Windows::Foundation::IInspectable,
    impl::consume_t<ITreeViewItemTemplateSettings>
{
    ITreeViewItemTemplateSettings(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ITreeViewItemTemplateSettingsFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<ITreeViewItemTemplateSettingsFactory>
{
    ITreeViewItemTemplateSettingsFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ITreeViewItemTemplateSettingsStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<ITreeViewItemTemplateSettingsStatics>
{
    ITreeViewItemTemplateSettingsStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ITreeViewList :
    Windows::Foundation::IInspectable,
    impl::consume_t<ITreeViewList>
{
    ITreeViewList(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ITreeViewListFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<ITreeViewListFactory>
{
    ITreeViewListFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ITreeViewNode :
    Windows::Foundation::IInspectable,
    impl::consume_t<ITreeViewNode>
{
    ITreeViewNode(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ITreeViewNodeFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<ITreeViewNodeFactory>
{
    ITreeViewNodeFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ITreeViewNodeStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<ITreeViewNodeStatics>
{
    ITreeViewNodeStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ITreeViewStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<ITreeViewStatics>
{
    ITreeViewStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ITwoPaneView :
    Windows::Foundation::IInspectable,
    impl::consume_t<ITwoPaneView>
{
    ITwoPaneView(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ITwoPaneViewFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<ITwoPaneViewFactory>
{
    ITwoPaneViewFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ITwoPaneViewStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<ITwoPaneViewStatics>
{
    ITwoPaneViewStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IUniformGridLayout :
    Windows::Foundation::IInspectable,
    impl::consume_t<IUniformGridLayout>
{
    IUniformGridLayout(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IUniformGridLayoutFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IUniformGridLayoutFactory>
{
    IUniformGridLayoutFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IUniformGridLayoutState :
    Windows::Foundation::IInspectable,
    impl::consume_t<IUniformGridLayoutState>
{
    IUniformGridLayoutState(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IUniformGridLayoutStateFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IUniformGridLayoutStateFactory>
{
    IUniformGridLayoutStateFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IUniformGridLayoutStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<IUniformGridLayoutStatics>
{
    IUniformGridLayoutStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IVirtualizingLayout :
    Windows::Foundation::IInspectable,
    impl::consume_t<IVirtualizingLayout>
{
    IVirtualizingLayout(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IVirtualizingLayoutContext :
    Windows::Foundation::IInspectable,
    impl::consume_t<IVirtualizingLayoutContext>
{
    IVirtualizingLayoutContext(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IVirtualizingLayoutContextFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IVirtualizingLayoutContextFactory>
{
    IVirtualizingLayoutContextFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IVirtualizingLayoutContextOverrides :
    Windows::Foundation::IInspectable,
    impl::consume_t<IVirtualizingLayoutContextOverrides>
{
    IVirtualizingLayoutContextOverrides(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IVirtualizingLayoutFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IVirtualizingLayoutFactory>
{
    IVirtualizingLayoutFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IVirtualizingLayoutOverrides :
    Windows::Foundation::IInspectable,
    impl::consume_t<IVirtualizingLayoutOverrides>
{
    IVirtualizingLayoutOverrides(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IXamlControlsResources :
    Windows::Foundation::IInspectable,
    impl::consume_t<IXamlControlsResources>
{
    IXamlControlsResources(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IXamlControlsResourcesStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<IXamlControlsResourcesStatics>
{
    IXamlControlsResourcesStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IZoomAnimationStartingEventArgs :
    Windows::Foundation::IInspectable,
    impl::consume_t<IZoomAnimationStartingEventArgs>
{
    IZoomAnimationStartingEventArgs(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IZoomCompletedEventArgs :
    Windows::Foundation::IInspectable,
    impl::consume_t<IZoomCompletedEventArgs>
{
    IZoomCompletedEventArgs(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IZoomOptions :
    Windows::Foundation::IInspectable,
    impl::consume_t<IZoomOptions>
{
    IZoomOptions(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IZoomOptionsFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IZoomOptionsFactory>
{
    IZoomOptionsFactory(std::nullptr_t = nullptr) noexcept {}
};

}
