// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.190111.3

#pragma once
#include "winrt/impl/Microsoft.UI.Xaml.Controls.0.h"
#include "winrt/impl/Windows.UI.0.h"
#include "winrt/impl/Windows.UI.Composition.0.h"
#include "winrt/impl/Windows.UI.Input.0.h"
#include "winrt/impl/Windows.UI.Xaml.0.h"
#include "winrt/impl/Windows.UI.Xaml.Controls.0.h"
#include "winrt/impl/Windows.UI.Xaml.Media.0.h"
#include "winrt/impl/Windows.UI.Xaml.Controls.Primitives.0.h"
#include "winrt/impl/Microsoft.UI.Xaml.Controls.Primitives.0.h"

WINRT_EXPORT namespace winrt::Microsoft::UI::Xaml::Controls::Primitives {

struct WINRT_EBO IColorPickerSlider :
    Windows::Foundation::IInspectable,
    impl::consume_t<IColorPickerSlider>
{
    IColorPickerSlider(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IColorPickerSliderFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IColorPickerSliderFactory>
{
    IColorPickerSliderFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IColorPickerSliderStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<IColorPickerSliderStatics>
{
    IColorPickerSliderStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IColorSpectrum :
    Windows::Foundation::IInspectable,
    impl::consume_t<IColorSpectrum>
{
    IColorSpectrum(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IColorSpectrumFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IColorSpectrumFactory>
{
    IColorSpectrumFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IColorSpectrumStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<IColorSpectrumStatics>
{
    IColorSpectrumStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ICommandBarFlyoutCommandBar :
    Windows::Foundation::IInspectable,
    impl::consume_t<ICommandBarFlyoutCommandBar>
{
    ICommandBarFlyoutCommandBar(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ICommandBarFlyoutCommandBarFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<ICommandBarFlyoutCommandBarFactory>
{
    ICommandBarFlyoutCommandBarFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ICommandBarFlyoutCommandBarTemplateSettings :
    Windows::Foundation::IInspectable,
    impl::consume_t<ICommandBarFlyoutCommandBarTemplateSettings>
{
    ICommandBarFlyoutCommandBarTemplateSettings(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO INavigationViewItemPresenter :
    Windows::Foundation::IInspectable,
    impl::consume_t<INavigationViewItemPresenter>
{
    INavigationViewItemPresenter(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO INavigationViewItemPresenterFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<INavigationViewItemPresenterFactory>
{
    INavigationViewItemPresenterFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO INavigationViewItemPresenterStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<INavigationViewItemPresenterStatics>
{
    INavigationViewItemPresenterStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRadioButtonsListView :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRadioButtonsListView>
{
    IRadioButtonsListView(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRadioButtonsListViewFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRadioButtonsListViewFactory>
{
    IRadioButtonsListViewFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRadioButtonsListViewItem :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRadioButtonsListViewItem>
{
    IRadioButtonsListViewItem(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRadioButtonsListViewItemFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRadioButtonsListViewItemFactory>
{
    IRadioButtonsListViewItemFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRepeatedScrollSnapPoint :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRepeatedScrollSnapPoint>
{
    IRepeatedScrollSnapPoint(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRepeatedScrollSnapPointFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRepeatedScrollSnapPointFactory>
{
    IRepeatedScrollSnapPointFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRepeatedZoomSnapPoint :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRepeatedZoomSnapPoint>
{
    IRepeatedZoomSnapPoint(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IRepeatedZoomSnapPointFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IRepeatedZoomSnapPointFactory>
{
    IRepeatedZoomSnapPointFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IScrollController :
    Windows::Foundation::IInspectable,
    impl::consume_t<IScrollController>
{
    IScrollController(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IScrollControllerInteractionRequestedEventArgs :
    Windows::Foundation::IInspectable,
    impl::consume_t<IScrollControllerInteractionRequestedEventArgs>
{
    IScrollControllerInteractionRequestedEventArgs(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IScrollControllerInteractionRequestedEventArgsFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IScrollControllerInteractionRequestedEventArgsFactory>
{
    IScrollControllerInteractionRequestedEventArgsFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IScrollControllerScrollByRequestedEventArgs :
    Windows::Foundation::IInspectable,
    impl::consume_t<IScrollControllerScrollByRequestedEventArgs>
{
    IScrollControllerScrollByRequestedEventArgs(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IScrollControllerScrollByRequestedEventArgsFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IScrollControllerScrollByRequestedEventArgsFactory>
{
    IScrollControllerScrollByRequestedEventArgsFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IScrollControllerScrollFromRequestedEventArgs :
    Windows::Foundation::IInspectable,
    impl::consume_t<IScrollControllerScrollFromRequestedEventArgs>
{
    IScrollControllerScrollFromRequestedEventArgs(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IScrollControllerScrollFromRequestedEventArgsFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IScrollControllerScrollFromRequestedEventArgsFactory>
{
    IScrollControllerScrollFromRequestedEventArgsFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IScrollControllerScrollToRequestedEventArgs :
    Windows::Foundation::IInspectable,
    impl::consume_t<IScrollControllerScrollToRequestedEventArgs>
{
    IScrollControllerScrollToRequestedEventArgs(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IScrollControllerScrollToRequestedEventArgsFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IScrollControllerScrollToRequestedEventArgsFactory>
{
    IScrollControllerScrollToRequestedEventArgsFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IScrollSnapPoint :
    Windows::Foundation::IInspectable,
    impl::consume_t<IScrollSnapPoint>
{
    IScrollSnapPoint(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IScrollSnapPointBase :
    Windows::Foundation::IInspectable,
    impl::consume_t<IScrollSnapPointBase>
{
    IScrollSnapPointBase(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IScrollSnapPointBaseFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IScrollSnapPointBaseFactory>
{
    IScrollSnapPointBaseFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IScrollSnapPointFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IScrollSnapPointFactory>
{
    IScrollSnapPointFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IScroller :
    Windows::Foundation::IInspectable,
    impl::consume_t<IScroller>
{
    IScroller(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IScrollerFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IScrollerFactory>
{
    IScrollerFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IScrollerStatics :
    Windows::Foundation::IInspectable,
    impl::consume_t<IScrollerStatics>
{
    IScrollerStatics(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISnapPointBase :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISnapPointBase>
{
    ISnapPointBase(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO ISnapPointBaseFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISnapPointBaseFactory>
{
    ISnapPointBaseFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IZoomSnapPoint :
    Windows::Foundation::IInspectable,
    impl::consume_t<IZoomSnapPoint>
{
    IZoomSnapPoint(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IZoomSnapPointBase :
    Windows::Foundation::IInspectable,
    impl::consume_t<IZoomSnapPointBase>
{
    IZoomSnapPointBase(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IZoomSnapPointBaseFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IZoomSnapPointBaseFactory>
{
    IZoomSnapPointBaseFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IZoomSnapPointFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IZoomSnapPointFactory>
{
    IZoomSnapPointFactory(std::nullptr_t = nullptr) noexcept {}
};

}
