// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.190111.3

#pragma once

WINRT_EXPORT namespace winrt::Windows::UI::Xaml::Interop {

struct TypeName;

}

WINRT_EXPORT namespace winrt::Windows::UI::Xaml::Markup {

struct IXamlType;
struct XmlnsDefinition;

}

WINRT_EXPORT namespace winrt::Windows::UI::Xaml::Markup {

struct IXamlMetadataProvider;

}

WINRT_EXPORT namespace winrt::Microsoft::UI::Xaml::XamlTypeInfo {

struct IXamlControlsXamlMetaDataProvider;
struct IXamlControlsXamlMetaDataProviderStatics;
struct XamlControlsXamlMetaDataProvider;

}

namespace winrt::impl {

template <> struct category<Microsoft::UI::Xaml::XamlTypeInfo::IXamlControlsXamlMetaDataProvider>{ using type = interface_category; };
template <> struct category<Microsoft::UI::Xaml::XamlTypeInfo::IXamlControlsXamlMetaDataProviderStatics>{ using type = interface_category; };
template <> struct category<Microsoft::UI::Xaml::XamlTypeInfo::XamlControlsXamlMetaDataProvider>{ using type = class_category; };
template <> struct name<Microsoft::UI::Xaml::XamlTypeInfo::IXamlControlsXamlMetaDataProvider>{ static constexpr auto & value{ L"Microsoft.UI.Xaml.XamlTypeInfo.IXamlControlsXamlMetaDataProvider" }; };
template <> struct name<Microsoft::UI::Xaml::XamlTypeInfo::IXamlControlsXamlMetaDataProviderStatics>{ static constexpr auto & value{ L"Microsoft.UI.Xaml.XamlTypeInfo.IXamlControlsXamlMetaDataProviderStatics" }; };
template <> struct name<Microsoft::UI::Xaml::XamlTypeInfo::XamlControlsXamlMetaDataProvider>{ static constexpr auto & value{ L"Microsoft.UI.Xaml.XamlTypeInfo.XamlControlsXamlMetaDataProvider" }; };
template <> struct guid_storage<Microsoft::UI::Xaml::XamlTypeInfo::IXamlControlsXamlMetaDataProvider>{ static constexpr guid value{ 0x17FA3F58,0x3472,0x5AA2,{ 0xA0,0xF8,0x1A,0xB8,0xA5,0x19,0x57,0x3D } }; };
template <> struct guid_storage<Microsoft::UI::Xaml::XamlTypeInfo::IXamlControlsXamlMetaDataProviderStatics>{ static constexpr guid value{ 0x2D7EB3FD,0xECDB,0x5084,{ 0xB7,0xE0,0x12,0xF9,0x59,0x83,0x81,0xEF } }; };
template <> struct default_interface<Microsoft::UI::Xaml::XamlTypeInfo::XamlControlsXamlMetaDataProvider>{ using type = Windows::UI::Xaml::Markup::IXamlMetadataProvider; };

template <> struct abi<Microsoft::UI::Xaml::XamlTypeInfo::IXamlControlsXamlMetaDataProvider>{ struct type : IInspectable
{
};};

template <> struct abi<Microsoft::UI::Xaml::XamlTypeInfo::IXamlControlsXamlMetaDataProviderStatics>{ struct type : IInspectable
{
    virtual int32_t WINRT_CALL Initialize() noexcept = 0;
};};

template <typename D>
struct consume_Microsoft_UI_Xaml_XamlTypeInfo_IXamlControlsXamlMetaDataProvider
{
};
template <> struct consume<Microsoft::UI::Xaml::XamlTypeInfo::IXamlControlsXamlMetaDataProvider> { template <typename D> using type = consume_Microsoft_UI_Xaml_XamlTypeInfo_IXamlControlsXamlMetaDataProvider<D>; };

template <typename D>
struct consume_Microsoft_UI_Xaml_XamlTypeInfo_IXamlControlsXamlMetaDataProviderStatics
{
    void Initialize() const;
};
template <> struct consume<Microsoft::UI::Xaml::XamlTypeInfo::IXamlControlsXamlMetaDataProviderStatics> { template <typename D> using type = consume_Microsoft_UI_Xaml_XamlTypeInfo_IXamlControlsXamlMetaDataProviderStatics<D>; };

}
