// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.190111.3

#pragma once
#include "winrt/impl/Windows.UI.1.h"
#include "winrt/impl/Windows.UI.Xaml.1.h"
#include "winrt/impl/Windows.UI.Composition.1.h"
#include "winrt/impl/Windows.UI.Xaml.Media.1.h"
#include "winrt/impl/Microsoft.UI.Xaml.Media.1.h"

WINRT_EXPORT namespace winrt::Microsoft::UI::Xaml::Media {

}

namespace winrt::impl {

}

WINRT_EXPORT namespace winrt::Microsoft::UI::Xaml::Media {

struct WINRT_EBO AcrylicBrush :
    Microsoft::UI::Xaml::Media::IAcrylicBrush,
    impl::base<AcrylicBrush, Windows::UI::Xaml::Media::XamlCompositionBrushBase, Windows::UI::Xaml::Media::Brush, Windows::UI::Xaml::DependencyObject>,
    impl::require<AcrylicBrush, Windows::UI::Composition::IAnimationObject, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2, Windows::UI::Xaml::Media::IBrush, Windows::UI::Xaml::Media::IBrushOverrides2, Windows::UI::Xaml::Media::IXamlCompositionBrushBase, Windows::UI::Xaml::Media::IXamlCompositionBrushBaseOverrides, Windows::UI::Xaml::Media::IXamlCompositionBrushBaseProtected>
{
    AcrylicBrush(std::nullptr_t) noexcept {}
    AcrylicBrush();
    static Windows::UI::Xaml::DependencyProperty BackgroundSourceProperty();
    static Windows::UI::Xaml::DependencyProperty TintColorProperty();
    static Windows::UI::Xaml::DependencyProperty TintOpacityProperty();
    static Windows::UI::Xaml::DependencyProperty TintTransitionDurationProperty();
    static Windows::UI::Xaml::DependencyProperty AlwaysUseFallbackProperty();
    static Windows::UI::Xaml::DependencyProperty TintLuminosityOpacityProperty();
};

struct WINRT_EBO RevealBackgroundBrush :
    Microsoft::UI::Xaml::Media::IRevealBackgroundBrush,
    impl::base<RevealBackgroundBrush, Microsoft::UI::Xaml::Media::RevealBrush, Windows::UI::Xaml::Media::XamlCompositionBrushBase, Windows::UI::Xaml::Media::Brush, Windows::UI::Xaml::DependencyObject>,
    impl::require<RevealBackgroundBrush, Microsoft::UI::Xaml::Media::IRevealBrush, Windows::UI::Composition::IAnimationObject, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2, Windows::UI::Xaml::Media::IBrush, Windows::UI::Xaml::Media::IBrushOverrides2, Windows::UI::Xaml::Media::IXamlCompositionBrushBase, Windows::UI::Xaml::Media::IXamlCompositionBrushBaseOverrides, Windows::UI::Xaml::Media::IXamlCompositionBrushBaseProtected>
{
    RevealBackgroundBrush(std::nullptr_t) noexcept {}
    RevealBackgroundBrush();
};

struct WINRT_EBO RevealBorderBrush :
    Microsoft::UI::Xaml::Media::IRevealBorderBrush,
    impl::base<RevealBorderBrush, Microsoft::UI::Xaml::Media::RevealBrush, Windows::UI::Xaml::Media::XamlCompositionBrushBase, Windows::UI::Xaml::Media::Brush, Windows::UI::Xaml::DependencyObject>,
    impl::require<RevealBorderBrush, Microsoft::UI::Xaml::Media::IRevealBrush, Windows::UI::Composition::IAnimationObject, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2, Windows::UI::Xaml::Media::IBrush, Windows::UI::Xaml::Media::IBrushOverrides2, Windows::UI::Xaml::Media::IXamlCompositionBrushBase, Windows::UI::Xaml::Media::IXamlCompositionBrushBaseOverrides, Windows::UI::Xaml::Media::IXamlCompositionBrushBaseProtected>
{
    RevealBorderBrush(std::nullptr_t) noexcept {}
    RevealBorderBrush();
};

struct WINRT_EBO RevealBrush :
    Microsoft::UI::Xaml::Media::IRevealBrush,
    impl::base<RevealBrush, Windows::UI::Xaml::Media::XamlCompositionBrushBase, Windows::UI::Xaml::Media::Brush, Windows::UI::Xaml::DependencyObject>,
    impl::require<RevealBrush, Windows::UI::Composition::IAnimationObject, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2, Windows::UI::Xaml::Media::IBrush, Windows::UI::Xaml::Media::IBrushOverrides2, Windows::UI::Xaml::Media::IXamlCompositionBrushBase, Windows::UI::Xaml::Media::IXamlCompositionBrushBaseOverrides, Windows::UI::Xaml::Media::IXamlCompositionBrushBaseProtected>
{
    RevealBrush(std::nullptr_t) noexcept {}
    static Windows::UI::Xaml::DependencyProperty ColorProperty();
    static Windows::UI::Xaml::DependencyProperty TargetThemeProperty();
    static Windows::UI::Xaml::DependencyProperty AlwaysUseFallbackProperty();
    static Windows::UI::Xaml::DependencyProperty StateProperty();
    static void SetState(Windows::UI::Xaml::UIElement const& element, Microsoft::UI::Xaml::Media::RevealBrushState const& value);
    static Microsoft::UI::Xaml::Media::RevealBrushState GetState(Windows::UI::Xaml::UIElement const& element);
};

}
