// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.190111.3

#pragma once
#include "winrt/impl/Windows.UI.Xaml.Interop.0.h"
#include "winrt/impl/Windows.UI.Xaml.Markup.0.h"
#include "winrt/impl/Microsoft.UI.Xaml.Markup.0.h"
#include "winrt/impl/Windows.Foundation.0.h"
#include "winrt/impl/Windows.UI.Composition.0.h"
#include "winrt/impl/Windows.UI.Xaml.0.h"
#include "winrt/impl/Windows.UI.Xaml.Controls.0.h"
#include "winrt/impl/MyApp.0.h"

WINRT_EXPORT namespace winrt::MyApp {

struct WINRT_EBO IApp :
    Windows::Foundation::IInspectable,
    impl::consume_t<IApp>
{
    IApp(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IMainUserControl :
    Windows::Foundation::IInspectable,
    impl::consume_t<IMainUserControl>
{
    IMainUserControl(std::nullptr_t = nullptr) noexcept {}
};

}
