// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.181115.3

#pragma once

#include "winrt/base.h"


static_assert(winrt::check_version(CPPWINRT_VERSION, "1.0.181115.3"), "Mismatched component and base headers.");
#include "winrt/Windows.Foundation.h"
#include "winrt/Windows.Foundation.Collections.h"
#include "winrt/impl/Windows.UI.Xaml.Interop.2.h"
#include "winrt/impl/Windows.UI.Xaml.Markup.2.h"
#include "winrt/impl/Windows.UI.Composition.2.h"
#include "winrt/impl/Windows.UI.Xaml.2.h"
#include "winrt/impl/Windows.UI.Xaml.Controls.2.h"
#include "winrt/impl/NativeWinRTComponent.2.h"

namespace winrt::impl {

template <typename D> int32_t consume_NativeWinRTComponent_IClass<D>::MyProperty() const
{
    int32_t value{};
    check_hresult(WINRT_SHIM(NativeWinRTComponent::IClass)->get_MyProperty(&value));
    return value;
}

template <typename D> void consume_NativeWinRTComponent_IClass<D>::MyProperty(int32_t value) const
{
    check_hresult(WINRT_SHIM(NativeWinRTComponent::IClass)->put_MyProperty(value));
}

template <typename D> int32_t consume_NativeWinRTComponent_IMyUserControl<D>::MyProperty() const
{
    int32_t value{};
    check_hresult(WINRT_SHIM(NativeWinRTComponent::IMyUserControl)->get_MyProperty(&value));
    return value;
}

template <typename D> void consume_NativeWinRTComponent_IMyUserControl<D>::MyProperty(int32_t value) const
{
    check_hresult(WINRT_SHIM(NativeWinRTComponent::IMyUserControl)->put_MyProperty(value));
}

template <typename D>
struct produce<D, NativeWinRTComponent::IClass> : produce_base<D, NativeWinRTComponent::IClass>
{
    int32_t WINRT_CALL get_MyProperty(int32_t* value) noexcept final
    {
        try
        {
            typename D::abi_guard guard(this->shim());
            WINRT_ASSERT_DECLARATION(MyProperty, WINRT_WRAP(int32_t));
            *value = detach_from<int32_t>(this->shim().MyProperty());
            return 0;
        }
        catch (...) { return to_hresult(); }
    }

    int32_t WINRT_CALL put_MyProperty(int32_t value) noexcept final
    {
        try
        {
            typename D::abi_guard guard(this->shim());
            WINRT_ASSERT_DECLARATION(MyProperty, WINRT_WRAP(void), int32_t);
            this->shim().MyProperty(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
    }
};

template <typename D>
struct produce<D, NativeWinRTComponent::IMyUserControl> : produce_base<D, NativeWinRTComponent::IMyUserControl>
{
    int32_t WINRT_CALL get_MyProperty(int32_t* value) noexcept final
    {
        try
        {
            typename D::abi_guard guard(this->shim());
            WINRT_ASSERT_DECLARATION(MyProperty, WINRT_WRAP(int32_t));
            *value = detach_from<int32_t>(this->shim().MyProperty());
            return 0;
        }
        catch (...) { return to_hresult(); }
    }

    int32_t WINRT_CALL put_MyProperty(int32_t value) noexcept final
    {
        try
        {
            typename D::abi_guard guard(this->shim());
            WINRT_ASSERT_DECLARATION(MyProperty, WINRT_WRAP(void), int32_t);
            this->shim().MyProperty(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
    }
};

}

WINRT_EXPORT namespace winrt::NativeWinRTComponent {

inline Class::Class() :
    Class(impl::call_factory<Class>([](auto&& f) { return f.template ActivateInstance<Class>(); }))
{}

inline MyUserControl::MyUserControl() :
    MyUserControl(impl::call_factory<MyUserControl>([](auto&& f) { return f.template ActivateInstance<MyUserControl>(); }))
{}

inline XamlMetaDataProvider::XamlMetaDataProvider() :
    XamlMetaDataProvider(impl::call_factory<XamlMetaDataProvider>([](auto&& f) { return f.template ActivateInstance<XamlMetaDataProvider>(); }))
{}

}

namespace winrt::impl {

struct property_NativeWinRTComponent_IClass
{ struct named {
    struct MyProperty
    {
        struct name { static constexpr std::wstring_view value{ L"MyProperty"sv }; };
        using property_type = int32_t;
        using target_type = winrt::NativeWinRTComponent::IClass;

        using is_readable = std::true_type;
        using is_writable = std::true_type;
        using is_static = std::false_type;
        struct getter
        {
            auto operator()(target_type const& target) const
            {
                return target.MyProperty();
            }
        };
        struct setter
        {
            template <typename Value>
            void operator()(target_type const& target, Value&& value) const
            {
                target.MyProperty(std::forward<Value>(value));
            }
        };
    };};
    struct list { using type = impl::typelist<named::MyProperty>; };
};

struct property_NativeWinRTComponent_IMyUserControl
{ struct named {
    struct MyProperty
    {
        struct name { static constexpr std::wstring_view value{ L"MyProperty"sv }; };
        using property_type = int32_t;
        using target_type = winrt::NativeWinRTComponent::IMyUserControl;

        using is_readable = std::true_type;
        using is_writable = std::true_type;
        using is_static = std::false_type;
        struct getter
        {
            auto operator()(target_type const& target) const
            {
                return target.MyProperty();
            }
        };
        struct setter
        {
            template <typename Value>
            void operator()(target_type const& target, Value&& value) const
            {
                target.MyProperty(std::forward<Value>(value));
            }
        };
    };};
    struct list { using type = impl::typelist<named::MyProperty>; };
};

struct property_NativeWinRTComponent_Class
{ struct named {
    struct MyProperty
    {
        struct name { static constexpr std::wstring_view value{ L"MyProperty"sv }; };
        using property_type = int32_t;
        using target_type = winrt::NativeWinRTComponent::Class;

        using is_readable = std::true_type;
        using is_writable = std::true_type;
        using is_static = std::false_type;
        struct getter
        {
            auto operator()(target_type const& target) const
            {
                return target.MyProperty();
            }
        };
        struct setter
        {
            template <typename Value>
            void operator()(target_type const& target, Value&& value) const
            {
                target.MyProperty(std::forward<Value>(value));
            }
        };
    };};
    struct list { using type = impl::typelist<named::MyProperty>; };
};

struct property_NativeWinRTComponent_MyUserControl
{ struct named {
    struct MyProperty
    {
        struct name { static constexpr std::wstring_view value{ L"MyProperty"sv }; };
        using property_type = int32_t;
        using target_type = winrt::NativeWinRTComponent::MyUserControl;

        using is_readable = std::true_type;
        using is_writable = std::true_type;
        using is_static = std::false_type;
        struct getter
        {
            auto operator()(target_type const& target) const
            {
                return target.MyProperty();
            }
        };
        struct setter
        {
            template <typename Value>
            void operator()(target_type const& target, Value&& value) const
            {
                target.MyProperty(std::forward<Value>(value));
            }
        };
    };};
    struct list { using type = impl::typelist<named::MyProperty>; };
};

}

WINRT_EXPORT namespace winrt::experimental::reflect {
template <> struct named_property<NativeWinRTComponent::IClass> : impl::property_NativeWinRTComponent_IClass::named {};
template <> struct properties<NativeWinRTComponent::IClass> : impl::property_NativeWinRTComponent_IClass::list {};
template <> struct named_property<NativeWinRTComponent::IMyUserControl> : impl::property_NativeWinRTComponent_IMyUserControl::named {};
template <> struct properties<NativeWinRTComponent::IMyUserControl> : impl::property_NativeWinRTComponent_IMyUserControl::list {};
template <> struct named_property<NativeWinRTComponent::Class> : impl::property_NativeWinRTComponent_Class::named {};
template <> struct properties<NativeWinRTComponent::Class> : impl::property_NativeWinRTComponent_Class::list {};
template <> struct named_property<NativeWinRTComponent::MyUserControl> : impl::property_NativeWinRTComponent_MyUserControl::named {};
template <> struct properties<NativeWinRTComponent::MyUserControl> : impl::property_NativeWinRTComponent_MyUserControl::list {};

template <>
struct base_type<NativeWinRTComponent::MyUserControl> { using type = Windows::UI::Xaml::Controls::Page; };
}

WINRT_EXPORT namespace std {

template<> struct hash<winrt::NativeWinRTComponent::IClass> : winrt::impl::hash_base<winrt::NativeWinRTComponent::IClass> {};
template<> struct hash<winrt::NativeWinRTComponent::IMyUserControl> : winrt::impl::hash_base<winrt::NativeWinRTComponent::IMyUserControl> {};
template<> struct hash<winrt::NativeWinRTComponent::Class> : winrt::impl::hash_base<winrt::NativeWinRTComponent::Class> {};
template<> struct hash<winrt::NativeWinRTComponent::MyUserControl> : winrt::impl::hash_base<winrt::NativeWinRTComponent::MyUserControl> {};
template<> struct hash<winrt::NativeWinRTComponent::XamlMetaDataProvider> : winrt::impl::hash_base<winrt::NativeWinRTComponent::XamlMetaDataProvider> {};

}
